# Generated by Django 2.2.6 on 2019-10-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gtin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin_number', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'GTIN NUMBER',
                'verbose_name_plural': 'GTIN NUMBER',
            },
        ),
    ]
